name: GVM Deploy
on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
      domain:
        required: true
        type: string
    secrets:
      ftp:
        required: true
        
jobs:
  gvm-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v3
    
    - name: ğŸ—ï¸ Build with 11ty
      run: |
        npm install @11ty/eleventy
        npx @11ty/eleventy --output=public_html
        
    - name: ã€½ï¸ Compress with Minify
      run: |
        cd public_html
        npm i minify@7.0.0 -g
        apt-get update
        apt-get -y install moreutils

        find . -type f \( -iname \*.html -o -iname \*.js -o -iname \*.css \) | while read fname
          do
          minify ${fname} | sponge ${fname}
          done   

    - name: ğŸ“¨ FTPS files
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: ${{inputs.domain}}
        username: gvm@${{inputs.domain}}
        password: ${{secrets.ftp}}
        local-dir: ./public_html/
        server-dir: ${{inputs.directory}}
        protocol: ftps
