name: GVM Compress
on:
  workflow_call:

jobs:
  web-compress:
    name: ğŸ—œï¸Compress
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2
        with:

      - name: ã€½ï¸ Minify
        uses: anthonyftwang/minify-action@v1.0.1

      - name: ğŸ“‚ Sync files
      - uses: stefanzweifel/git-auto-commit-action@v4
  
